Update ebs.yml

diff --git a/.github/workflows/ebs.yml b/.github/workflows/ebs.yml
--- a/.github/workflows/ebs.yml
+++ b/.github/workflows/ebs.yml
@@ -7,13 +7,9 @@ jobs:
 
     steps:
       - name: Install AWS CLI
-        run: sudo apt install awscli
-
-#       - name: Get Stacks
-#         env: 
-#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#         run: aws elasticbeanstalk list-available-solution-stacks --region us-east-1
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y awscli jq
 
       - name: Set up AWS credentials
         env: 
@@ -23,25 +19,38 @@ jobs:
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set region us-east-1
+
+      - name: Create EC2 key pair and store in Secrets Manager
+        run: |
+            KEY_NAME="testkey"
+            SECRET_NAME="MytestkeyPrivateKey"
+            
+            # Create the key pair
+            PRIVATE_KEY=$(aws ec2 create-key-pair --key-name $KEY_NAME | jq -r '.KeyMaterial')
+            
+            # Try to create the secret. This will fail silently if the secret already exists.
+            aws secretsmanager create-secret --name $SECRET_NAME --secret-string "$PRIVATE_KEY" --cli-input-idempotent || true
+            
+            # Update the secret. This will work whether or not the secret was just created.
+            aws secretsmanager put-secret-value --secret-id $SECRET_NAME --secret-string "$PRIVATE_KEY"
           
       - name: Create instance profile and associate role
         run: |
           aws iam get-instance-profile --instance-profile-name test-instance-profile \
           || (aws iam create-instance-profile --instance-profile-name test-instance-profile &&
           aws iam add-role-to-instance-profile --role-name my-role --instance-profile-name test-instance-profile)
-
+          
       - name: Create Elastic Beanstalk Application
         run: | 
           aws elasticbeanstalk describe-applications --application-name my-app \
           || aws elasticbeanstalk create-application --application-name my-app --description "My application for Elastic Beanstalk"
-
+          
       - name: Provision Elastic Beanstalk instance
         run: |
           aws elasticbeanstalk create-environment \
             --application-name my-app \
             --environment-name my-env \
-            --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=test-instance-profile \
-            Namespace=aws:ec2:instances,OptionName=KeyName,Value=docs \
+            --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=test-instance-profile,OptionName=KeyName,Value=testkey \
             --region us-east-1 \
             --tier Type=Standard,Name=WebServer \
             --solution-stack-name "64bit Amazon Linux 2023 v4.0.3 running Python 3.9"
